language: rust
cache:
  directories:
    - $HOME/kcov-i686-unknown-linux-gnu
    - $HOME/kcov-x86_64-unknown-linux-gnu
    - $HOME/android/android-sdk-linux
    - $HOME/android/android-18-arm-linux-androideabi-4.8
matrix:
  include:
    - env: TARGET_X=armv7-linux-androideabi CC_X=arm-linux-androideabi-clang CXX_X=arm-linux-androideabi-clang++ FEATURES_X=--features=rsa_signing MODE_X=DEBUG KCOV=0
      rust: stable
      os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - expect
            - openjdk-6-jre-headless
          sources:
            - ubuntu-toolchain-r-test

    - env: TARGET_X=armv7-linux-androideabi CC_X=arm-linux-androideabi-clang CXX_X=arm-linux-androideabi-clang++ FEATURES_X= MODE_X=DEBUG KCOV=0
      rust: stable
      os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - expect
            - openjdk-6-jre-headless
          sources:
            - ubuntu-toolchain-r-test

    - env: TARGET_X=armv7-linux-androideabi CC_X=arm-linux-androideabi-clang CXX_X=arm-linux-androideabi-clang++ FEATURES_X=--features=rsa_signing MODE_X=RELWITHDEBINFO KCOV=0
      rust: stable
      os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - expect
            - openjdk-6-jre-headless
          sources:
            - ubuntu-toolchain-r-test

    - env: TARGET_X=armv7-linux-androideabi CC_X=arm-linux-androideabi-clang CXX_X=arm-linux-androideabi-clang++ FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0
      rust: stable
      os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - expect
            - openjdk-6-jre-headless
          sources:
            - ubuntu-toolchain-r-test

script: mk/travis.sh
