language: rust
matrix:
  fast_finish: true
  include:
    - env: TARGET_X=aarch64-unknown-linux-gnu CC_X=aarch64-linux-gnu-gcc CXX_X=aarch64-linux-gnu-g++ MODE_X=DEBUG KCOV=1
      rust: nightly
      sudo: required
      dist: trusty
      before_install:
        - sudo add-apt-repository ppa:pietro-monteiro/qemu-backport -y
        - sudo apt-get update -qq
        - sudo apt-get install binfmt-support gcc-aarch64-linux-gnu gcc-4.8-aarch64-linux-gnu g++-aarch64-linux-gnu g++-4.8-aarch64-linux-gnu libc6-dev-arm64-cross qemu-user-binfmt -y
        - sudo apt-get install dpkg-cross -y

script: if [[ "$TARGET_X" == "arm-unknown-linux-gnueabi" ]]; then travis_wait 60 mk/travis.sh; else mk/travis.sh; fi
