language: rust
matrix:
  fast_finish: true
  include:
    - env: TARGET_X=aarch64-unknown-linux-gnu CC_X=aarch64-linux-gnu-gcc CXX_X=aarch64-linux-gnu-g++ MODE_X=DEBUG KCOV=1
      rust: nightly
      sudo: required
      dist: trusty
      before_install:
        - sudo dpkg --add-architecture arm64
        - sudo add-apt-repository 'deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ trusty main' -y
        - sudo add-apt-repository ppa:pietro-monteiro/qemu-backport -y
        - sudo apt-get update -qq || echo "updated"
        - sudo apt-get install binfmt-support dpkg-cross gcc-aarch64-linux-gnu gcc-4.8-aarch64-linux-gnu g++-aarch64-linux-gnu g++-4.8-aarch64-linux-gnu libc6-dev-arm64-cross pkg-config-aarch64-linux-gnu qemu-user-binfmt -y

script: mk/travis.sh
