language: rust
matrix:
  fast_finish: true
  include:
    - env: TARGET_X=arm-linux-androideabi CC_X=arm-linux-androideabi DOCKER=alexcrichton/rust-slave-android:2015-11-22
      rust: nightly
      sudo: required
      dist: trusty
      services:
        - docker

script: mk/travis.sh
