language: rust
rust:
  - stable
cache:
  directories:
    - $HOME/kcov-i686-unknown-linux-gnu
    - $HOME/kcov-x86_64-unknown-linux-gnu
matrix:
  include:
    - env: TARGET_X=armv7-linux-androideabi CC_X=arm-linux-androideabi-clang CXX_X=arm-linux-androideabi-clang++ FEATURES_X=--features=rsa_signing MODE_X=DEBUG KCOV=0
      os: linux
      dist: trusty
      sudo: required
      android:
        components:
          - build-tools-24.4.1
          - android-18
          - sys-img-armeabi-v7a-android-18

    - env: TARGET_X=armv7-linux-androideabi CC_X=arm-linux-androideabi-clang CXX_X=arm-linux-androideabi-clang++ FEATURES_X= MODE_X=DEBUG KCOV=0
      os: linux
      dist: trusty
      sudo: required
      android:
        components:
          - build-tools-24.4.1
          - android-18
          - sys-img-armeabi-v7a-android-18

    - env: TARGET_X=armv7-linux-androideabi CC_X=arm-linux-androideabi-clang CXX_X=arm-linux-androideabi-clang++ FEATURES_X=--features=rsa_signing MODE_X=RELWITHDEBINFO KCOV=0
      os: linux
      dist: trusty
      sudo: required
      android:
        components:
          - build-tools-24.4.1
          - android-18
          - sys-img-armeabi-v7a-android-18

    - env: TARGET_X=armv7-linux-androideabi CC_X=arm-linux-androideabi-clang CXX_X=arm-linux-androideabi-clang++ FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0
      os: linux
      dist: trusty
      sudo: required
      android:
        components:
          - build-tools-24.4.1
          - android-18
          - sys-img-armeabi-v7a-android-18


script: if [[ "$TARGET_X" =~ ^a*.*linux-.*eabi && "$MODE_X" == "RELWITHDEBINFO" ]]; then travis_wait 60 mk/travis.sh; else mk/travis.sh; fi
