language: rust
cache:
  directories:
    - $HOME/kcov-i686-unknown-linux-gnu
    - $HOME/kcov-x86_64-unknown-linux-gnu
    - $HOME/android/android-ndk
    - $HOME/android/android-sdk-linux/platform-tools
    - $HOME/android/android-sdk-linux/tools
matrix:
  include:
    - env: TARGET_X=aarch64-linux-android CC_X=aarch64-linux-android-clang CXX_X=aarch64-linux-android-clang++ FEATURES_X=--features=rsa_signing MODE_X=DEBUG KCOV=0
      rust: stable
      os: linux
      dist: trusty
      sudo: required

    - env: TARGET_X=aarch64-linux-android CC_X=aarch64-linux-android-clang CXX_X=aarch64-linux-android-clang++ FEATURES_X= MODE_X=DEBUG KCOV=0
      rust: stable
      os: linux
      dist: trusty
      sudo: required

    - env: TARGET_X=aarch64-linux-android CC_X=aarch64-linux-android-clang CXX_X=aarch64-linux-android-clang++ FEATURES_X=--features=rsa_signing MODE_X=RELWITHDEBINFO KCOV=0
      rust: stable
      os: linux
      dist: trusty
      sudo: required

    - env: TARGET_X=aarch64-linux-android CC_X=aarch64-linux-android-clang CXX_X=aarch64-linux-android-clang++ FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0
      rust: stable
      os: linux
      dist: trusty
      sudo: required

    - env: TARGET_X=armv7-linux-androideabi CC_X=arm-linux-androideabi-clang CXX_X=arm-linux-androideabi-clang++ FEATURES_X=--features=rsa_signing MODE_X=DEBUG KCOV=0
      rust: stable
      os: linux
      dist: trusty
      sudo: required

    - env: TARGET_X=armv7-linux-androideabi CC_X=arm-linux-androideabi-clang CXX_X=arm-linux-androideabi-clang++ FEATURES_X= MODE_X=DEBUG KCOV=0
      rust: stable
      os: linux
      dist: trusty
      sudo: required

    - env: TARGET_X=armv7-linux-androideabi CC_X=arm-linux-androideabi-clang CXX_X=arm-linux-androideabi-clang++ FEATURES_X=--features=rsa_signing MODE_X=RELWITHDEBINFO KCOV=0
      rust: stable
      os: linux
      dist: trusty
      sudo: required

    - env: TARGET_X=armv7-linux-androideabi CC_X=arm-linux-androideabi-clang CXX_X=arm-linux-androideabi-clang++ FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0
      rust: stable
      os: linux
      dist: trusty
      sudo: required

script: mk/travis.sh
